{% set version = "3.2.7" %}

package:
    name: subprocess32
    version: {{ version }}

source:
    fn: subprocess32-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/s/subprocess32/subprocess32-{{ version }}.tar.gz
    md5: 824c801e479d3e916879aae3e9c15e16

build:
    number: 0
    skip: True  # [not py2k]
    script: python setup.py install

requirements:
    host:
        - python

    build:
        - {{ compiler('c') }}

    run:
        - python

test:
    imports:
        - subprocess32

about:
    home: https://github.com/google/python-subprocess32
    license: PSF 2
    license_family: PSF
    summary: 'A backport of the subprocess module from Python 3.2/3.3 for use on 2.x.'
    
    description: |
      This is a backport of the Python 3 subprocess module for use on Python 2. 
      This code has not been tested on Windows or other non-POSIX platforms.
      subprocess32 includes many important reliability bug fixes relevant on POSIX platforms. 
      The most important of which is a C extension module used internally to handle the code 
      path between fork() and exec(). This module is reliable when an application is using threads.
    doc_url: https://docs.python.org/3.3/library/subprocess.html
    dev_url: https://github.com/google/python-subprocess32
    doc_source_url: 

extra:
  recipe-maintainers:
    - tacaswell
    - mdboom
