{% set version = "3.5.4" %}

package:
  name: subprocess32
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/subprocess32/subprocess32-{{ version }}.tar.gz
  sha256: eb2937c80497978d181efa1b839ec2d9622cf9600a039a79d0e108d1f9aec79d

build:
  number: 0
  skip: True  # [not py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - subprocess32

about:
  home: https://github.com/google/python-subprocess32
  license: PSF 2
  summary: 'A backport of the subprocess module from Python 3.2/3.3 for use on 2.x.'

extra:
  recipe-maintainers:
    - tacaswell
    - mdboom
