{% set version = "3.5.0" %}

package:
  name: subprocess32
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/subprocess32/subprocess32-{{ version }}.tar.gz
  sha256: a24bac119f23fac0e53a3707b5539b214350ddd4d7d49c87d5f3be297ca1607a

build:
  number: 0
  skip: True  # [not py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - subprocess32

about:
  home: https://github.com/google/python-subprocess32
  license: PSF 2
  summary: 'A backport of the subprocess module from Python 3.2/3.3 for use on 2.x.'

extra:
  recipe-maintainers:
    - tacaswell
    - mdboom
