# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J2PUcyd+1TMYV1wAWYjXnMswZWhhNiHZ2AeHi0gMQvfLVttm4g363AivOJ0ILvL76JiZj/V6JXju0XHu9UJ9jRq0+TUXmBagAdiSodEEry1HdnGokbAoAgdvh+4cvE3HjbYGlEHmgFzwgkkg2dpONz11rxxLMRtpqPbHimJHg6zO/6OXqouB+yJT2yOiSXKXf0TSWssT+aDaeWExDPwT74mPxUg/+EFqUsZDjm2KxRgoMzvlM/hZy3Tyj7g09ywAgL9CvOwC8yF4J/tT3nlAOLwJylVKeXd/Sx0Ynanym8vHKvQjSgsYGMHpXuTUr7l1ZJU+z2MfJahGyToP40RM2G3hiGuAJ1WhG+gmfAysy3Iw5+xZtbqAW8wrKPMjoa5Q+xsOlgr9Wzs7RtYEGmWdq+MQ0Ubrk3YK3wxSXL/x1oodCaZFQVPIn3lxjmvSRLNVF7ki0wBBqYe2zC+E3ygQBU6zDjuvQ2/4G9E4jVfiuOqWjM0nLG0xcMufyhCbPE5+r+u0KugGjrw2FYSaKgvTJEFZv22ybZUeTCSKAoaXPbXn+U6bG1E1KsufzrmNNqk9/c7h6DzwbmxdArxv3gNwSOYsuXOAAaLOYxQOV50jd9LhGxsJexJUJnCATUH6SFqWq+pN71WPv1ySpxH/PA8rcDG/EhXRrs+9zv7NjsGmLVU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
