# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J2PUcyd+1TMYV1wAWYjXnMswZWhhNiHZ2AeHi0gMQvfLVttm4g363AivOJ0ILvL76JiZj/V6JXju0XHu9UJ9jRq0+TUXmBagAdiSodEEry1HdnGokbAoAgdvh+4cvE3HjbYGlEHmgFzwgkkg2dpONz11rxxLMRtpqPbHimJHg6zO/6OXqouB+yJT2yOiSXKXf0TSWssT+aDaeWExDPwT74mPxUg/+EFqUsZDjm2KxRgoMzvlM/hZy3Tyj7g09ywAgL9CvOwC8yF4J/tT3nlAOLwJylVKeXd/Sx0Ynanym8vHKvQjSgsYGMHpXuTUr7l1ZJU+z2MfJahGyToP40RM2G3hiGuAJ1WhG+gmfAysy3Iw5+xZtbqAW8wrKPMjoa5Q+xsOlgr9Wzs7RtYEGmWdq+MQ0Ubrk3YK3wxSXL/x1oodCaZFQVPIn3lxjmvSRLNVF7ki0wBBqYe2zC+E3ygQBU6zDjuvQ2/4G9E4jVfiuOqWjM0nLG0xcMufyhCbPE5+r+u0KugGjrw2FYSaKgvTJEFZv22ybZUeTCSKAoaXPbXn+U6bG1E1KsufzrmNNqk9/c7h6DzwbmxdArxv3gNwSOYsuXOAAaLOYxQOV50jd9LhGxsJexJUJnCATUH6SFqWq+pN71WPv1ySpxH/PA8rcDG/EhXRrs+9zv7NjsGmLVU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
