travis:
  secure:
    BINSTAR_TOKEN: J2PUcyd+1TMYV1wAWYjXnMswZWhhNiHZ2AeHi0gMQvfLVttm4g363AivOJ0ILvL76JiZj/V6JXju0XHu9UJ9jRq0+TUXmBagAdiSodEEry1HdnGokbAoAgdvh+4cvE3HjbYGlEHmgFzwgkkg2dpONz11rxxLMRtpqPbHimJHg6zO/6OXqouB+yJT2yOiSXKXf0TSWssT+aDaeWExDPwT74mPxUg/+EFqUsZDjm2KxRgoMzvlM/hZy3Tyj7g09ywAgL9CvOwC8yF4J/tT3nlAOLwJylVKeXd/Sx0Ynanym8vHKvQjSgsYGMHpXuTUr7l1ZJU+z2MfJahGyToP40RM2G3hiGuAJ1WhG+gmfAysy3Iw5+xZtbqAW8wrKPMjoa5Q+xsOlgr9Wzs7RtYEGmWdq+MQ0Ubrk3YK3wxSXL/x1oodCaZFQVPIn3lxjmvSRLNVF7ki0wBBqYe2zC+E3ygQBU6zDjuvQ2/4G9E4jVfiuOqWjM0nLG0xcMufyhCbPE5+r+u0KugGjrw2FYSaKgvTJEFZv22ybZUeTCSKAoaXPbXn+U6bG1E1KsufzrmNNqk9/c7h6DzwbmxdArxv3gNwSOYsuXOAAaLOYxQOV50jd9LhGxsJexJUJnCATUH6SFqWq+pN71WPv1ySpxH/PA8rcDG/EhXRrs+9zv7NjsGmLVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
